spring.application.name=springboot-intro

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml

jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}
